insurance_companies = [
    "Abu Dhabi National Ins. Co.",
    "Abu Dhabi National Takaful",
    "Al Ain Ahlia Insurance Co",
    "Al Buhaira National Insurance Co",
    "Al Dhafra National Ins. Co",
    "Al Fujairah National Ins. Co",
    "Al Wathba National Insurance Co",
    "Al Khazna Insurance Co",
    "Al Sagr National Ins. Co",
    "Alliance Insurance Co",
    "Arabian Scandinavian Ins. Co",
    "Arabic Islamic Ins. Co.",
    "Dar Al Takaful",
    "Dubai Insurance Co.",
    "Dubai Islamic Ins. & Reins. Co.",
    "Dubai National Ins. & Reins. Co",
    "Emirates Insurance Co.",
    "Fidelity United Insurance Co.",
    "Insurance House",
    "Methaq Takaful Insurance Co",
    "National General Insurance Co",
    "National Health Insurance Co.",
    "Noor Takaful General",
    "Noor Takaful Family",
    "Oman Insurance Co.",
    "Orient Insurance Co.",
    "Orient UNB Takaful",
    "RAK National Insurance Co.",
    "Union Insurance Company",
    "Sharjah Insurance Co",
    "Takaful Emarat",
    "HAYAH Insurance",
    "National Takaful Company",
    "Yas Takaful"
]